# Generated by Django 4.0.1 on 2022-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
