# Generated by Django 4.0.1 on 2022-02-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0006_alter_report_options_remove_csv_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
